# Generated by Django 5.1.7 on 2025-06-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bandera',
        ),
        migrations.DeleteModel(
            name='Bandera',
        ),
    ]
