# Generated by Django 5.1.7 on 2025-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
