# Generated by Django 5.1.7 on 2025-04-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=50)),
                ('icono_url', models.URLField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('bandera', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuarios', models.ManyToManyField(related_name='copilotos', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('bandera', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuarios', models.ManyToManyField(related_name='pilotos', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.CharField(max_length=10)),
                ('equipo', models.CharField(blank=True, max_length=255)),
                ('coche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.coche')),
                ('copiloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.copiloto')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rally.piloto')),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='rally.rally')),
            ],
        ),
    ]
