# Generated by Django 5.1.7 on 2025-04-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rally', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacionrally',
            name='coche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.coche'),
        ),
        migrations.AddField(
            model_name='participacionrally',
            name='copiloto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.copiloto'),
        ),
        migrations.AddField(
            model_name='participacionrally',
            name='piloto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.piloto'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='pilotos',
            field=models.ManyToManyField(blank=True, to='rally.piloto'),
        ),
        migrations.AddField(
            model_name='participacionrally',
            name='rally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rally.rally'),
        ),
    ]
