# Generated by Django 5.1.7 on 2025-04-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='icono_url',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='marca_modelo',
        ),
        migrations.RemoveField(
            model_name='copiloto',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='coche',
            name='modelo',
            field=models.CharField(default='Desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coche',
            name='puntos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copiloto',
            name='puntos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='puntos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='copiloto',
            name='bandera',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='bandera',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rally',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10)),
                ('coches', models.ManyToManyField(blank=True, to='rally.coche')),
                ('copilotos', models.ManyToManyField(blank=True, to='rally.copiloto')),
                ('pilotos', models.ManyToManyField(blank=True, to='rally.piloto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionRally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(blank=True, max_length=255)),
                ('dorsal', models.CharField(blank=True, max_length=10)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('puntos', models.IntegerField(default=0)),
                ('coche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.coche')),
                ('copiloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.copiloto')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rally.piloto')),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rally.rally')),
            ],
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
