# Generated by Django 5.1.7 on 2025-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='nombre',
            field=models.CharField(default='Mi equipo', max_length=255),
        ),
    ]
