# Generated by Django 5.1.7 on 2025-06-01 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0004_fantasyteam_puntos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeamRally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('coches', models.ManyToManyField(blank=True, to='rally.coche')),
                ('copilotos', models.ManyToManyField(blank=True, to='rally.copiloto')),
                ('pilotos', models.ManyToManyField(blank=True, to='rally.piloto')),
                ('rally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rally.rally')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rally')},
            },
        ),
    ]
