# Generated by Django 5.1.7 on 2025-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0006_copiloto_precio_minimo_piloto_precio_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiloto',
            name='precio_minimo',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='precio_minimo',
        ),
    ]
