# Generated by Django 5.1.7 on 2025-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0007_remove_copiloto_precio_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rally',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rally',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
