# Generated by Django 5.1.7 on 2025-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0008_rally_fecha_fin_rally_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=10),
        ),
    ]
