# Generated by Django 5.1.7 on 2025-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0009_alter_fantasyteam_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
